---
version: "3"

tasks:
  default:
    desc: List all available tasks.
    cmds:
      - task --list-all
    silent: true

  generate:
    desc: Build BPF files and generate Go code.
    sources:
      - ./internal/bpf/src/*.{h,c}
    generates:
      - ./internal/bpf/bpf_bpfel.{go,o}
      - ./internal/bpf/bpf_bpfeb.{go,o}
    cmds:
      - bpftool btf dump file /sys/kernel/btf/vmlinux format c >
        ./internal/bpf/include/vmlinux.h
      - go tool bpf2go -tags linux -output-dir ./internal/bpf -go-package bpf
        BPF ./internal/bpf/src/fix.c

  build:
    desc: Build the goland-fix-go-15787 Go binary.
    deps:
      - generate
    cmds:
      - go build -trimpath -o ./bin/goland-fix-go-15787
    sources:
      - ./go.{mod,sum}
      - ./**.go
    generates:
      - ./bin/goland-fix-go-15787

  clean:
    desc: Delete generated artifacts.
    cmds:
      - rm -rf ./bin/
      - rm -rf ./internal/bpf/include/*.h
      - rm -f ./internal/bpf/*.{go,o}
