// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadBPF returns the embedded CollectionSpec for BPF.
func LoadBPF() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BPFBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load BPF: %w", err)
	}

	return spec, err
}

// LoadBPFObjects loads BPF and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BPFObjects
//	*BPFPrograms
//	*BPFMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBPFObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBPF()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BPFSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BPFSpecs struct {
	BPFProgramSpecs
	BPFMapSpecs
	BPFVariableSpecs
}

// BPFProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BPFProgramSpecs struct {
	SysEnterExecve *ebpf.ProgramSpec `ebpf:"sys_enter_execve"`
}

// BPFMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BPFMapSpecs struct {
	Logs *ebpf.MapSpec `ebpf:"logs"`
}

// BPFVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BPFVariableSpecs struct {
}

// BPFObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type BPFObjects struct {
	BPFPrograms
	BPFMaps
	BPFVariables
}

func (o *BPFObjects) Close() error {
	return _BPFClose(
		&o.BPFPrograms,
		&o.BPFMaps,
	)
}

// BPFMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type BPFMaps struct {
	Logs *ebpf.Map `ebpf:"logs"`
}

func (m *BPFMaps) Close() error {
	return _BPFClose(
		m.Logs,
	)
}

// BPFVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type BPFVariables struct {
}

// BPFPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type BPFPrograms struct {
	SysEnterExecve *ebpf.Program `ebpf:"sys_enter_execve"`
}

func (p *BPFPrograms) Close() error {
	return _BPFClose(
		p.SysEnterExecve,
	)
}

func _BPFClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BPFBytes []byte
